### ISSUE TITLE
Doesnt download contents

### ISSUE THREAD

**Issue by lhaasper** [Retransition/Server-Sided-Files#2]
https://cdn.discordapp.com/attachments/692109248875724861/706252585182429700/unknown.png
https://cdn.discordapp.com/attachments/692109248875724861/706252617428369448/unknown.png
https://cdn.discordapp.com/attachments/692109248875724861/706252655411986522/unknown.png

Please help me.

**Comment by biitez** [comment]
@lhaasper I don't know if you've already solved it, but if not yet, I hope to help you, the server is waiting for the code name, with the value 5, you are sending the name 5 with the value 5

![image](https://user-images.githubusercontent.com/60155141/95821474-59a3cc00-0d00-11eb-9cb0-099aad3103b3.png)
